### ISSUE TITLE
Revisions and refinements for MLA 8 basic citations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#500]
This ticket follows work in #415 to generate a basic citation in MLA 8th edition style. See that ticket for additional references.

Simplified example of MLA 8 output:

> Blamires, Harry. _The New Bloomsday Book: A Guide through Ulysses_. 3rd ed., Routledge, 1996.

After testing, a few formatting issues and refinements have been identified:

1. Basic formatting issues; Capitalization (Title Case)
2. Author name formatting
3. Displaying editors vs. authors
4. Displaying DOIs if available: we have done this for APA already in #417

**1. Punctuation and capitalization**

- We're missing a period after the author name. 
- The final element of the citation should be prefaced with a comma not a period.
- The title should be in Title Case, which means significant words should be capitalized and not just the first word.

Example: 990027503070302486

Current output - see highlights where changes are needed

![Screen Shot 2021-04-30 at 11.08.41 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6254c169-599b-43ab-9b80-9999ef31685f)

Desired output - see highlights to show changes

![Screen Shot 2021-04-30 at 11.08.50 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7abf7db5-516d-41e2-9c3e-6641ca22ffbc)

**2. Author name formatting**
In some cases our 1xxx authors have additional qualifiers such as spelling out initials, birth/death dates, etc. We should trim this down so that it is just the last name and first name if possible (essentially the 1XX $a only).

The example below shows a name with qualifiers:
https://blackcat-arch.library.emory.edu/catalog/990027503070302486

`100 1  a| Yeats, W. B. q| (William Butler), d| 1865-1939.`

Current output
![Screen Shot 2021-04-30 at 11.18.11 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d8333ae0-2dcd-4875-ae59-417b08edb93b)

Desired output
![Screen Shot 2021-04-30 at 11.08.50 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/41384428-9c33-437b-8370-1ba76f661b79)

**3: Editors vs. authors formatting**
https://blackcat-arch.library.emory.edu/catalog/9936777323402486
For some records we don't have a 1xx author, and are showing editors/translators etc. as if they were authors. 

Current output

> Gleason, Abbott _A companion to Russian history_. Blackwell. 2007.

Desired output

Simple option: remove the editor and just show the title first. 
> _A Companion to Russian History_. Blackwell. 2007.

Complex option: detect if the name is an editor vs. some other role. Display the editor as formatted below - see `, editor` added after the name. Note, this also shows the revised capitalization and punctuation noted above in # 1.

> Gleason, Abbot, editor. _A Companion to Russian History_. Blackwell. 2007.

**4. Displaying DOIs if available**
Below is an example of formatting a citation for a book that has a DOI assigned. Work has been done to enable this for APA already in #417.

In this case, the DOI becomes the last element in the citation and should be prefaced with a comma and end with a period.

> Author. _Title of container (self contained if book)_, Version (edition), Number (vol. and/or no.), Publisher, Publication Date, DOI. 

For the same example noted in # 2 above, this would be: 

> _A Companion to Russian History_. Blackwell. 2007, doi: 10.1002/9781444308419.

**Comment by eporter23** [comment]
@alexBLR revisions look good! A couple of things:

For the doi example, there should be a comma between the year and the doi:

![Screen Shot 2021-05-14 at 12.39.53 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/45cea246-9732-41a1-a62d-669eae0883c0)

I'm also seeing that the ending period seems to be missing for the MLA citations. Whatever components are populated, the citation should end with a period.

![Screen Shot 2021-05-14 at 12.54.15 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e144ad03-91fe-4e78-b571-c48f1faf51e5)

**Comment by bwatson78** [comment]
@alexBLR I just deployed to Test with the latest code and am seeing errors:
```
F, [2021-05-20T13:24:08.449285 #1562] FATAL -- : [e533bbe6-38a1-4216-b260-c0d4674215a4] ActionView::Template::Error (undefined method `rstrip' for 1868:Integer):
F, [2021-05-20T13:24:08.449433 #1562] FATAL -- : [e533bbe6-38a1-4216-b260-c0d4674215a4]     15:   <% @documents.each do |document| %>
[e533bbe6-38a1-4216-b260-c0d4674215a4]     16:     <% if document.respond_to?(:export_as_mla_citation_txt) %>
[e533bbe6-38a1-4216-b260-c0d4674215a4]     17:       <h2><%= t('blacklight.citation.mla') %></h2>
[e533bbe6-38a1-4216-b260-c0d4674215a4]     18:       <%= document.send(:export_as_mla_citation_txt).html_safe %><br/><br/>
[e533bbe6-38a1-4216-b260-c0d4674215a4]     19:     <% end %>
[e533bbe6-38a1-4216-b260-c0d4674215a4]     20:
[e533bbe6-38a1-4216-b260-c0d4674215a4]     21:     <% if document.respond_to?(:export_as_apa_citation_txt) %>
F, [2021-05-20T13:24:08.449483 #1562] FATAL -- : [e533bbe6-38a1-4216-b260-c0d4674215a4]
F, [2021-05-20T13:24:08.449514 #1562] FATAL -- : [e533bbe6-38a1-4216-b260-c0d4674215a4] app/models/concerns/blacklight/solr/document/marc_export.rb:438:in `get_publisher_info_from_solr_mla'
[e533bbe6-38a1-4216-b260-c0d4674215a4] app/models/concerns/blacklight/solr/document/marc_export.rb:319:in `mla_citation'
[e533bbe6-38a1-4216-b260-c0d4674215a4] app/models/concerns/blacklight/solr/document/marc_export.rb:36:in `export_as_mla_citation_txt'
[e533bbe6-38a1-4216-b260-c0d4674215a4] app/views/catalog/_citation.html.erb:18:in `block in _app_views_catalog__citation_html_erb__1093404640260012032_70227487903360'
[e533bbe6-38a1-4216-b260-c0d4674215a4] app/views/catalog/_citation.html.erb:15:in `each'
[e533bbe6-38a1-4216-b260-c0d4674215a4] app/views/catalog/_citation.html.erb:15:in `_app_views_catalog__citation_html_erb__1093404640260012032_70227487903360'
```
I'm not sure that stripping whitespace there would fix it. I'm guessing you may have to abandon the joining of array elements and go to building up a return string, so that you could add `, #{clean_end_punctuation(doi)` to the string without an extra space. That way, you could check for the presence of a comma at the end of the current string and format appropriately.

**Comment by eporter23** [comment]
@alexBLR I was testing this on arch. The doi addition looks great but the ending period on the citation is still missing on all citations now.

Current output:
_A Companion to Russian History_. Blackwell, 2007, doi: 10.1002/9781444308419  

Desired output:
_A Companion to Russian History_. Blackwell, 2007, doi: 10.1002/9781444308419**.**  

Related example:

_A Companion to Russian History_. Wiley-Blackwell, 2009

should be

_A Companion to Russian History_. Wiley-Blackwell, 2009**.**

**Comment by eporter23** [comment]
@alexBLR I'm still not seeing a period at the end of the MLA citations. Is that still in progress?

**Comment by alexBLR** [comment]
![Screen Shot 2021-06-04 at 9.52.48 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/d318184c-3722-476e-ab51-836075b1b879)

![Screen Shot 2021-06-04 at 9.52.28 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/bde7e464-e9a3-4e99-9df5-d9d859c9907e)

**Comment by lovinscari** [comment]
@eporter23 - Can you please review this when you have time and close if acceptable? Thanks.

**Comment by eporter23** [comment]
@alexBLR and @lovinscari we'll close this one and I'll write a new one specific to the capitalization style. Thanks!
